### ISSUE TITLE
Testing statuses and commands with cucumber?

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp#1]
I've started to experiment with cucumber and I've managed to establish communication.

But how does I test commands and statuses with cucumber? And how do I wait for an expected result?

**Comment by emiltin** [comment]
Did you have a look at https://github.com/rsmp-nordic/rsmp_validator? It shows how to test commands and statuses, and how to wait for results.

Testing site: https://github.com/rsmp-nordic/rsmp_validator/tree/master/spec/site
Testing supervisor: https://github.com/rsmp-nordic/rsmp_validator/tree/master/spec/supervisor

rsmp_validator uses RSpec, not Cucumber, but Cucumber is really just a layer on top of RSpec. The Cucumber step definitions would use code similar to what the rsmp_validator RSpec tests uses.

The rsmp gem interface for waiting for reponses could be more consistent. Currenty site.request_status() waits for the respons and return it. While site.send_command() returns immediately and you then use site.wait_for_command_response() to wait for the response.

**Comment by emiltin** [comment]
Did the above answer you question? Can this issue be closed?

**Comment by otterdahl** [comment]
Yes. This issue can be closed
