### ISSUE TITLE
AggretatedStatus field fP should not default to nil?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp#11]
When sending an AggregatedStatus message, the functional position field (fP) and the functional state field (fS) are always set to nil.

I guess the value should be supplied by the relevant grouped component?

Is there a default value?

Is a null value allowed according to the rsmp spec (schema)?

**Comment by emiltin** [comment]
I noticed that MobiMaestro does not allow a fP null value for TLC's.

**Comment by emiltin** [comment]
fixed in PR #13

**Comment by emiltin** [comment]
david any input on default/required values for the aggregated status?

**Comment by otterdahl** [comment]
According to the the [specification](https://rsmp-nordic.github.io/rsmp_core/applicability/basic_structure.html#id7) **fP** should be `null` if it not used (default). Otherwise, **fP** is a string, e.g. `"fP":"Dark"`

**Comment by emiltin** [comment]
Does each SXL have it's own list of valid strings?

**Comment by emiltin** [comment]
Looking at the SXL for traffic lights, I don't see any description of valid values for fP under the explanation of aggregated status:
https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/sxl_traffic_light_controller.html#aggregated-status

There is however some values mentioned under M0001:
https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/sxl_traffic_light_controller.html#m0001

**Comment by otterdahl** [comment]
> Does each SXL have it's own list of valid strings?

Correct. It's an array of valid strings

**Comment by otterdahl** [comment]
> Looking at the SXL for traffic lights, I don't see any description of valid values for fP under the explanation of aggregated status:
> https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/sxl_traffic_light_controller.html#aggregated-status



> 
> There is however some values mentioned under M0001:
> https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/sxl_traffic_light_controller.html#m0001

The SXL for traffic controllers doesn't use functional positions since version 1.0.1, since we were unsure how to define it in a good way for traffic signals. It was replaced with individual statuses instead. M0001 is the command equivalent.

**Comment by emiltin** [comment]
Hmm. I noticed that MobiMaestro requires fP to be 'NormalControl', otherwise the aggregated status is rejected.

**Comment by otterdahl** [comment]
That is strange. That must clearly be a bug.

**Comment by otterdahl** [comment]
I would recommend you open an issue for this at https://github.com/rsmp-nordic/rsmp_implementations/issues

**Comment by emiltin** [comment]
OK. But I think this is not very clear in the SXL spec for traffic lights.

**Comment by emiltin** [comment]
M0001 is called 'Functional position'. Why is aggregated status not usd for this?

**Comment by otterdahl** [comment]
> M0001 is called 'Functional position'. Why is aggregated status not used for this?

It's a command, not a status

**Comment by emiltin** [comment]
Ah yes

**Comment by emiltin** [comment]
I guess we should revert back to setting fP to null by default then?

**Comment by otterdahl** [comment]
> I guess we should revert back to setting fP to null by default then?
> 
Yes. In order to comply with spec

**Comment by emiltin** [comment]
with df964d3 fP is (again) set to nil when sending aggregated status. i guess this will later have to be differentiated if other types of equipment uses other values.

**Comment by emiltin** [comment]
pushed with 23d4119d16be
