### ISSUE TITLE
improve handling of timeouts + async tasks

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp#14]
There are issues with the handling of timeouts. If a site is slow and causes timeout in a test, it can cause other tests to fail.
It's probably due to how exceptions and async tasks plays together in RSMP::Supervisor, RSMP::SiteProxy, etc.

**Comment by otterdahl** [comment]
Does this happen with the built in tlc simulator?

**Comment by emiltin** [comment]
I saw it with the ruby tlc. it's fixed
