### ISSUE TITLE
git submodule: needed?

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp#24]
I noticed that .gitmodules is empty, but the readme states that you should run:

```
git submodule init
git submodule fetch
```

Is this needed?

**Comment by emiltin** [comment]
You're right, it's not needed anymore. I think it was from when the json schema was included as a submodule, but now it's a gem, and the submodules are handled inside the gem.

**Comment by emiltin** [comment]
fixed by #36
