### ISSUE TITLE
CLI Message Testing

### ISSUE THREAD

**Issue by DavidAdamsBluecity** [rsmp-nordic/rsmp#42]
Hello. I've been working on an API implementation of RSMP Nordic. Is there is any way to test the sending and receiving of custom-made messages between Site and Supervisor, particularly without actual equipment connected?

I know the Windows app simulator seems able to do it, but I can't seem to find that capability in this gem so far. This would be helpful in my incorporation of RSMP. Is it possible?

**Comment by otterdahl** [comment]
Perhaps @emiltin is better at answering this question, but I don't think there is any built in method to do this with this tool right now, unless you edit the source.

If you needs custom messages, one method is to create a custom SXL (using Excel or YAML file) and import that into the Windows simulator.

**Comment by DavidAdamsBluecity** [comment]
Thanks. I'm more looking at how to send messages in an API scenario (for example, manually sending Command M0008 from one site equipment to another). If this isn't available with this tool, then I guess I'll have to modify it in some way, but I just wanted to make sure beforehand.

**Comment by otterdahl** [comment]
If command M0008 is all you need then you could do it with rsmp_validator this way:

Start the rsmp simulator in `rsmp/`. With this command it simulates a TLC.
```bash
$ bundle exec rsmp site
```
and then start rspec in rsmp_validator...
in `rsmp_validator/`
```bash
$ bundle exec rspec spec/site/tlc/detector_logics_spec.rb:39
```

That would make rspec:
1. Connect
2. Run the test case found on that particular line in that file (detector_logics_spec.rb, line 39), and nothing else.
3. And then disconnect.

5. You can tweak the settings in `rsmp_validator/config/gem_tlc.yaml`, e.g. selecting detector logic.

The test case:
* Forces a detector logic with M0008 to True
* Verifies that the detector logic has been set to True by requesting status S0002
* Forces a detector logic with M0008 to False
* Verifies that the detector logic has been set to False by requesting status S0002

As you've noticed, the test cases very much focuses on testing the TLC. We have very few test cases that tests the supervision system (or other equipment acting as an supervision system).

If your equipment expects to receive an M0008 (as oppose to sending), then I suppose we don't have any tests cases that covers that yet.

**Comment by DavidAdamsBluecity** [comment]
Is there any way of incorporating the test case's method into the RSMP CLI implementation without breaking it?

**Comment by DavidAdamsBluecity** [comment]
Yes, I've already incorporated the rsmp_validator's message-sending methods into the rsmp gem, and the message sends  the command with a nack response returned, but it doesn't seem possible to call those functions after the site and supervisor are both waiting. Unless there's some interrupt function I'm overlooking.

**Comment by emiltin** [comment]
if you're trying to extend the CLI so you can manaully send and wait for messages, then you would need to add a command ike -i that enters an interactive mode. based on in input you can then send messages. but if just want to menually send a few messages, it's probably easier to use the ruby shell (irb) and use the RSMP classes programatically.

**Comment by DavidAdamsBluecity** [comment]
Even running in interactive mode, once the site or supervisor is connected and listening, there doesn't seem to be a way to input additional code without killing the process.

At this point, I'm able to send various messages adapted from the validator source code, all of which return a "Not Implemented" nack response (not sure if that's expected, but it seems to automatically be raised for every message, per the source code). Eventually I aim to be able to send messages like these regularly.  Right now, that only seems to be possible by restarting the site/supervisor in the CLI and sending the message (denoted by a message-specific flag) before waiting. Is there a simpler way of sending messages after the waiting/listening task has started?

**Comment by emiltin** [comment]
the rsmp gem uses the 'async' gem to handle asynchronous events. this makes it easy to e.g. run a supervisor in a background task, and then do do other things like send messages triggered by a timer. that's alsop how the rsmp_validator works.

but note that using irb (interactive ruby), it's hard to use the async functionality, because the irb console itself is not running inside an async reactor. there's an experimental way to run irb inside an async reactor at https://github.com/rsmp-nordic/rsmp/blob/master/bin/console.

**Comment by DavidAdamsBluecity** [comment]
Would it be possible to communicate elsewhere to discuss the prospect of message-sending in more depth?

**Comment by emiltin** [comment]
@DavidAdamsBluecity this repo is usually the best channel. if you have a repo with your code that you can share it can be helpful. unfortunately i'm still away from work, but perhaps @otterdahl can provide som input.

**Comment by DavidAdamsBluecity** [comment]
I have a private repo which I can't make public at the moment. I'm basically trying to set up the API so that it requests and receives signal and detector status at regular intervals, and sends a command when interactively told to do so. Doing so while navigating the asynchronous tasks created by this API is proving to be a difficult task.

**Comment by emiltin** [comment]
Are you using IRB, or extending the CLI of the rsmp gem?

If you use IRB, be sure to call ```Async { binding.irb}```to make Async work.

Here's an example of running an RSMP supervisor in IRB, starting a perioding task that fetches a status. You're still inside IRB and can can run any interactive stuff you want, like sending RSMP commands using the RSMP gem API. This example assumes you have a TLC (or emulator) running.

```shell
~ % irb
irb(main):001:0> require 'async'
=> true
irb(main):002:0> Async { binding.irb }                                            # make async task work in irb
irb(main):001:0> require 'rsmp'
=> true
irb(main):002:0> log_settings = { 'path' =>  'supervisor.log' }
=> {"path"=>"supervisor.log"}
irb(main):003:0> supervisor = RSMP::Supervisor.new( log_settings: log_settings )  # create a supervisor, log to file
=> #<RSMP::Supervisor:30140, @supervisor_settings: {"port"=>12111, "ips"=>"all", "guest"=>{"core_versions"=>"all", "sxl"=>"tlc", "intervals"=>{"t...
irb(main):004:0> supervisor_task = Async { supervisor.run }                       # run supervisor in a task
=> 
#<Async::Task:0x000000010d970208                                                                                                          
...                                                                                                                                       
irb(main):005:0> # Start an RMSP TLC connection to the supervisor. e.g. using 'rsmp site --type tlc --config config/my_tlc.yaml' in a terminal. 
irb(main):006:0> # You should see the site connecting if you look at the supervisor.log log file
=> nil
irb(main):007:0> 
irb(main):008:0* # Now you can interact with the site, e.g. to request status or send commands
irb(main):009:0*                                                                                           
irb(main):010:0> site = supervisor.proxies.first                                   # get our site object
=> #<RSMP::SiteProxy:68380, @node: #<RSMP::Supervisor:0x000000010da2bd50>, @archive: #<RSMP::Archive:0x000000010da2b968>, @logger: #<RSMP::Logger...
irb(main):011:0> site.components                                                   # show components
=> 
{"TC"=>
  #<RSMP::ComponentProxy:73700, @c_id: "TC", @ntsOId: nil, @xNId: nil, @node: #<RSMP::SiteProxy:0x000000010cefcd58>, @grouped: false, @aggregated_status: [], @aggregated_status_bools: [false, false, false, false, false, true, false, false], @alarms: {}, @statuses: {}, @allow_repeat_updates: {}>}
irb(main):012:0> # Start a task that request aggregated status once per second. Note that you can only
irb(main):013:0> # request aggregated status on the main component, so make sure to use the name matching your actual site
=> nil
irb(main):014:0> 
irb(main):015:0> state = ''
=> ""
irb(main):016:2* request_task = Async { loop {
irb(main):017:2*         sleep 1
irb(main):018:2*         result = site.request_status 'TC', [{'sCI'=>'S0001','n'=>'signalgroupstatus'}], collect: { timeout: 1}
irb(main):019:2*         state  = result[:collector].query_got_hash
irb(main):020:0> } } # start request task
=> 
#<Async::Task:0x000000010d832f80
...
irb(main):021:0> # This task now runs in the background, updating state once per second (if the tlc responds).
=> nil
irb(main):022:0> puts state         # check the latest state collected by the request_task
{"S0001"=>{"signalgroupstatus"=>"NB11"}}
=> nil                                                                                                                                                
irb(main):023:0> puts state         # check the latest state collected by the request_task
{"S0001"=>{"signalgroupstatus"=>"11BB"}}
irb(main):028:0> 
```

**Comment by DavidAdamsBluecity** [comment]
That makes sense. Thanks for the prompt response. I had been extending the CLI of the rsmp gem to allow sending messages using methods from the validator rspecs, but I guess it might be simpler to use an IRB method now that I have a better understanding of how to use the state_collector module. I'll give it a try.

**Comment by emiltin** [comment]
Making your own interactive CLI is also a possible way. IRB is flexible; you're writing code, with all the power that comes with that. a CLI on the other and can have an easy-to-use interface. A CLI would work basically as the IRB example above; you run some task in the background, than on another task/loop you wait for promt input (like sending commands).

**Comment by DavidAdamsBluecity** [comment]
Yes, immediately after I sent my last reply I tried plugging the solution into the CLI instead of an IRB. I think I had been under the impression that the Async task that tells the supervisor to start and wait was necessary, and that any other Async tasks would have to be created inside of it. Now it all makes more sense, and using .run in a separate Async task seems to simplify the issue.

The addition of a manual prompt also seems to work, although I still need to try it with some of site_proxy's other methods.

**Comment by emiltin** [comment]
Notice that that outermost Async block runs synchronously - subsequent commands will not run until it ends. So this script

```ruby
require 'async'
Async { sleep 1: puts 'a' }
puts 'b'
```

will wait one second, then print a and b. b is not printed until the async block has completed.

On the other hand, in the irb session example above, the supervisor is run in an Async block, but execution continues after the block immediately. Why? Because the earlier line ```Async { binding.irb }```causes an irb session that runs inside an Async block.

The take away is that if you want stuff to run concurrently, it must be inside a single top-level Async block. So this will not work:

```
async
   fetch status
async
  handle cli
```

whereas this will work:

```
async
  async
     fetch status
  async
     handle cli
```

Check out the async docs for more.
https://socketry.github.io/async/guides/getting-started/index.html
