### ISSUE TITLE
TLC emulator: reset alarm acknowledged to false

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp#46]
reset alarm acknowledge to false. 

should this happen whenever the alarm is change to active or inactive?

**Comment by emiltin** [comment]
@otterdahl input on this?

**Comment by otterdahl** [comment]
Whenever an alarm changes from inactive to active, it also becomes un-acknowledged.

**Comment by otterdahl** [comment]
There is a figure of possible alarm state transitions in [rsmp core](https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html#alarm-transitions)

**Comment by emiltin** [comment]
on that figure, i see only one state where ack=true, which is 'Active Acknowledged'. It seems the only time ack is set to false is when it goes active?

**Comment by otterdahl** [comment]
> on that figure, i see only one state where ack=true, which is 'Active Acknowledged'. It seems the only time ack is set to false is when it goes active?

Correct. Only when the alarm goes active.

It doesn't make sense to set ack=false when the alarm goes inactive, because an operator at the traffic management center needs to know if he/she has missed an alarm, which may have turned inactive since first turned active.

**Comment by emiltin** [comment]
implemented
