### ISSUE TITLE
refactor regex option in wait_for_status_update

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp#7]
wait_for_status_update accepts regex input, if the :regex options is set. i suggest we simply accept :s input in regex format. and remove the regex option:

so instead of:
```ruby
{ s:"[0-9]*", regex:true }
```

use:
```ruby
{ s:/[0-9]*/ }
```

**Comment by otterdahl** [comment]
Sound good

**Comment by emiltin** [comment]
done
