### ISSUE TITLE
The wait_for_alarm function should include ability to check timestamp

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp#9]
The wait_for_alarm function treats all alarms the same way regardless how old the timestamp is.

There should be a way to check timestamp to be within a certain range. Right now the only way to check that we have received the correct alarm is to check component, alarmCodeId, aSp and sS.

**Comment by emiltin** [comment]
can you explain this a bit more?

**Comment by emiltin** [comment]
ping @otterdahl

**Comment by otterdahl** [comment]
I don't remember. I'ts been too long since I've opended this issue .Feel free to close this issue.

**Comment by emiltin** [comment]
stale
